/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RNV
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        con = MySqlConnection.ConnectDb();
        //mod.setText(car1);
    }
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    String car1, brand1, name, cust_name;
    int pd1, cust_id, num, total;
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public void setCar(String brand, String car, String cust_name, int cust_id) {
    //this.userField.setText(user);
        brand1 = brand;
        name = car;
        this.cust_name = cust_name;
        this.cust_id = cust_id;
        car1 = brand + " " + car;
        nm.setText(this.cust_name);
        mod.setText(car1);
        String sql = "SELECT price FROM vehicles WHERE name = ?;";
        try{
        ps = con.prepareStatement(sql);
        ps.setString(1, name);
        rs = ps.executeQuery();
        rs.next();
        pd1 = rs.getInt("price");
        pd.setText(Integer.toString(pd1));
        /*Get the damned image*/
        byte[] imageBytes;
        Image image;
        ps = con.prepareStatement("SELECT image FROM vehicles WHERE name = ?;");
        ps.setString(1,name);
        rs = ps.executeQuery();
        while(rs.next())
        {
            imageBytes = rs.getBytes(1);
            image = getToolkit().createImage(imageBytes);
            ImageIcon icon = new ImageIcon(image);
            img.setIcon(icon);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        tprice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        pd = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        mod = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        numb = new javax.swing.JTextField();
        top = new javax.swing.JLabel();
        conf = new javax.swing.JToggleButton();
        price = new javax.swing.JLabel();
        nuber = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(null);

        img.setText("img");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 110, 230, 210);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 470, 73, 30);

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(710, 470, 80, 30);

        tprice.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        tprice.setText("Total: Rs.");
        getContentPane().add(tprice);
        tprice.setBounds(250, 290, 80, 30);

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel1.setText("Rs.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 190, 30, 30);

        tot.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        tot.setText("-");
        getContentPane().add(tot);
        tot.setBounds(330, 290, 110, 30);

        nm.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        nm.setText("jLabel1");
        getContentPane().add(nm);
        nm.setBounds(310, 110, 390, 20);

        pd.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        pd.setText("jLabel1");
        getContentPane().add(pd);
        pd.setBounds(400, 180, 100, 50);

        Name.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        Name.setText("Name:");
        getContentPane().add(Name);
        Name.setBounds(250, 110, 70, 20);

        mod.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        mod.setText("mod");
        getContentPane().add(mod);
        mod.setBounds(370, 140, 370, 40);

        car.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        car.setText("Car Selected:");
        getContentPane().add(car);
        car.setBounds(250, 140, 120, 40);

        numb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbActionPerformed(evt);
            }
        });
        getContentPane().add(numb);
        numb.setBounds(410, 240, 70, 30);

        top.setFont(new java.awt.Font("Raleway", 0, 20)); // NOI18N
        top.setText("Order Details");
        getContentPane().add(top);
        top.setBounds(10, 70, 260, 40);

        conf.setText("Calculate");
        conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confActionPerformed(evt);
            }
        });
        getContentPane().add(conf);
        conf.setBounds(510, 240, 80, 30);

        price.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        price.setText("Price Per Day:");
        getContentPane().add(price);
        price.setBounds(250, 190, 140, 30);

        nuber.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        nuber.setText("Number of days:");
        getContentPane().add(nuber);
        nuber.setBounds(250, 230, 160, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        bg.setText("jLabel1");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbActionPerformed

    private void confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confActionPerformed
        // TODO add your handling code here:
        try{
            num = Integer.parseInt(numb.getText());
            total = num * pd1;
            tot.setText(Integer.toString(total));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Invalid Number of Days");
        }
            
    }//GEN-LAST:event_confActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM license_plate WHERE model = ? and avail = 'y' LIMIT 1;";    //Extracting the first available instance
        String state_code = null;
        int license_no = 0;
        try{
            ps = con.prepareStatement(sql);
            ps.setString(1,name);
            rs = ps.executeQuery();
            rs.next();
            state_code = rs.getString("state_code");
            license_no = rs.getInt("license_no");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        
        String sql1 = "INSERT INTO booking (cust_id, days, fare, car_state, car_lic) VALUES (?,?,?,?,?);";
        try{
            ps = con.prepareStatement(sql1);
            ps.setInt(1,cust_id);
            ps.setInt(2, Integer.parseInt(numb.getText()));
            ps.setInt(3,total);
            ps.setString(4,state_code);
            ps.setInt(5,license_no);
            int i = ps.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null, "Order Placed!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        sql1 = "UPDATE vehicles SET avail = avail - 1 WHERE name = ?;"; //name
        int r;
        try{
            ps = con.prepareStatement(sql1);
            ps.setString(1,name);
            r = ps.executeUpdate();
            if(r>0)
            {
                JOptionPane.showMessageDialog(null,"update successful");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        mainscreen s = new mainscreen();
        s.setVisible(true);
        close();
    }//GEN-LAST:event_confirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel car;
    private javax.swing.JToggleButton conf;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mod;
    private javax.swing.JLabel nm;
    private javax.swing.JLabel nuber;
    private javax.swing.JTextField numb;
    private javax.swing.JLabel pd;
    private javax.swing.JLabel price;
    private javax.swing.JLabel top;
    private javax.swing.JLabel tot;
    private javax.swing.JLabel tprice;
    // End of variables declaration//GEN-END:variables
}
