/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RNV
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import AppPackage.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class cust_fill extends javax.swing.JFrame {
    /*SQL Connection varialbles*/
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    String customer_name;
    int customer_id;

    /**
     * Creates new form cust_fill
     */
    public cust_fill() {
        initComponents();
        con = MySqlConnection.ConnectDb();
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        lino = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        Domain = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(null);

        Next.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Next.setText("Next");
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
        });
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(710, 470, 73, 23);

        Back.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(20, 470, 61, 23);

        lino.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        lino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linoActionPerformed(evt);
            }
        });
        getContentPane().add(lino);
        lino.setBounds(20, 390, 330, 30);

        phno.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        phno.setToolTipText("");
        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        getContentPane().add(phno);
        phno.setBounds(60, 310, 220, 30);

        Domain.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Domain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomainActionPerformed(evt);
            }
        });
        getContentPane().add(Domain);
        Domain.setBounds(320, 230, 150, 30);

        user.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(20, 230, 260, 30);

        name.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(20, 150, 610, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cust_fill.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void DomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DomainActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnoActionPerformed

    private void linoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linoActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        cust_sel s = new cust_sel();
        s.setVisible(true);
        close();
    }//GEN-LAST:event_BackMouseClicked

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
        // TODO add your handling code here:
        
        //get all inputs
        int flag;
        String fname = name.getText();
        String ename = user.getText();
        String dom = Domain.getText();
        String email = ename + "@" + dom;
        String mob = phno.getText();
        if(mob.length() != 10)
        {
            flag = 0;
            JOptionPane.showMessageDialog(null,"Invalid Phone number");
        }
        //customer_name = fname;
        /*try{
            mob = Long.parseLong(phno.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,e);
            cust_fill s = new cust_fill();
            //s.setVisible(true);
            System.exit(0);
        }*/
        String li = lino.getText();
        
        String sql = "INSERT INTO customer (name,email,mobile,licence) VALUES (?,?,?,?)";
        try{
            ps = con.prepareStatement(sql);
            ps.setString(1,fname);
            ps.setString(2,email);
            ps.setString(3, mob);
            ps.setString(4,li);
            int i = ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"Entry Made!");
                //mainscreen s = new mainscreen();
                //s.setVisible(true);
                //close();
            }
            else{
                JOptionPane.showMessageDialog(null,"Somewhere something went terribly wrong!");
            }
            sql = "SELECT cust_id FROM customer WHERE email =  ?;";
            ps = con.prepareStatement(sql);
            ps.setString(1, email);
            rs = ps.executeQuery();
            rs.next();
            customer_id = rs.getInt("cust_id");
            JOptionPane.showMessageDialog(null,Integer.toString(customer_id));
            /*Next Page*/
            car_select s = new car_select();
            s.setNames(fname, customer_id);
            s.setVisible(true);
            close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        //JOptionPane.showMessageDialog(null,email);
    }//GEN-LAST:event_NextMouseClicked

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        /*car_select s = new car_select();
        s.setNames(customer_name, customer_id);
        s.setVisible(true);
        close();*/
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cust_fill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cust_fill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cust_fill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cust_fill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cust_fill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Domain;
    private javax.swing.JButton Next;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField lino;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
