/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RNV
 */
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

public class login extends javax.swing.JFrame {
Connection con = null;
PreparedStatement ps = null;
ResultSet rs = null;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        con = MySqlConnection.ConnectDb();
        
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        passwd = new javax.swing.JPasswordField();
        usrname = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(null);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(711, 480, 60, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rod.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 510, 810, 10);

        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pass.png"))); // NOI18N
        password.setText("jLabel3");
        getContentPane().add(password);
        password.setBounds(260, 190, 100, 60);

        username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        username.setText("jLabel2");
        getContentPane().add(username);
        username.setBounds(260, 110, 130, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 360, 170, 60);

        passwd.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        getContentPane().add(passwd);
        passwd.setBounds(260, 250, 270, 30);

        usrname.setFont(new java.awt.Font("Raleway", 0, 11)); // NOI18N
        usrname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrnameActionPerformed(evt);
            }
        });
        getContentPane().add(usrname);
        usrname.setBounds(260, 170, 270, 30);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_1.jpg"))); // NOI18N
        BG.setText("jLabel1");
        BG.setAutoscrolls(true);
        BG.setMaximumSize(new java.awt.Dimension(800, 520));
        BG.setMinimumSize(new java.awt.Dimension(800, 520));
        BG.setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().add(BG);
        BG.setBounds(0, 0, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usrnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrnameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        String sql = "SELECT * FROM staff WHERE name=? and password=?" ;
        try{
            ps = con.prepareStatement(sql);
            ps.setString(1,usrname.getText());
            ps.setString(2,passwd.getText());
            rs = ps.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Welcome user");
                mainscreen s = new mainscreen();
                s.setVisible(true);
                close();
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid Username or Password");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/submit_hov.png"));
        jLabel1.setIcon(II);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        ImageIcon III = new ImageIcon(getClass().getResource("/submit.png"));
        jLabel1.setIcon(III);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        ImageIcon IV = new ImageIcon(getClass().getResource("/submit_pr.png"));
        jLabel1.setIcon(IV);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/submit_hov.png"));
        jLabel1.setIcon(II);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usrname;
    // End of variables declaration//GEN-END:variables
}
