/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RNV
 */


import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class old_cust extends javax.swing.JFrame {

    /**
     * Creates new form old_cust
     */
    public old_cust() {
        initComponents();
        con = MySqlConnection.ConnectDb();
    }
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        cust_id = new javax.swing.JLabel();
        mobno = new javax.swing.JLabel();
        lic = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        c = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Raleway", 0, 11)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 110, 69, 30);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 460, 55, 30);
        getContentPane().add(cust_id);
        cust_id.setBounds(90, 394, 200, 20);

        mobno.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        getContentPane().add(mobno);
        mobno.setBounds(90, 280, 210, 30);

        lic.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        getContentPane().add(lic);
        lic.setBounds(130, 330, 280, 40);

        name.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        getContentPane().add(name);
        name.setBounds(60, 230, 400, 30);

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 460, 70, 30);

        c.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        c.setText("Customer ID:");
        getContentPane().add(c);
        c.setBounds(10, 394, 80, 20);

        l.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        l.setText("License Number:");
        getContentPane().add(l);
        l.setBounds(10, 330, 140, 40);

        m.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        m.setText("Mobile No.:");
        getContentPane().add(m);
        m.setBounds(10, 280, 90, 30);

        n.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        n.setText("Name:");
        getContentPane().add(n);
        n.setBounds(10, 230, 50, 30);

        jLabel2.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel2.setText("Customer Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 180, 170, 30);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(130, 110, 230, 30);

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel1.setText("Customer Email:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 120, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM customer WHERE email = ?;";
        try{
        ps = con.prepareStatement(sql);
        ps.setString(1,email.getText());
        rs = ps.executeQuery();
        if(rs.next()){
            name.setText(rs.getString("name"));
            mobno.setText(rs.getString("mobile"));
            lic.setText(rs.getString("licence"));
            cust_id.setText(rs.getString("cust_id"));
        }
        else{
            JOptionPane.showMessageDialog(null,"No customer found!");
            name.setText("");
            mobno.setText("");
            lic.setText("");
            cust_id.setText("");
        }
        /*if(rs.getString("name") == ""){
            JOptionPane.showMessageDialog(null, "No such customer!");
            name.setText("");
            mobno.setText("");
            lic.setText("");
            cust_id.setText("");
        }*/
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        close();
        cust_sel s = new cust_sel();
        s.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(name.getText() == "")
        {
            JOptionPane.showMessageDialog(null,"No customer selected!");
        }else{
            car_select s = new car_select();
            s.setNames(name.getText(), Integer.parseInt(cust_id.getText()));
            s.setVisible(true);
            close();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(old_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(old_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(old_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(old_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new old_cust().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel c;
    private javax.swing.JLabel cust_id;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l;
    private javax.swing.JLabel lic;
    private javax.swing.JLabel m;
    private javax.swing.JLabel mobno;
    private javax.swing.JLabel n;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
