/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RNV
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class return_car extends javax.swing.JFrame {

    /**
     * Creates new form return_car
     */
    public return_car() {
        initComponents();
        con = MySqlConnection.ConnectDb();
    }

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    String car_state, name, brand, model; 
    int car_lic, cust_id, days, fare;
    int flag = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JButton();
        back = new javax.swing.JButton();
        accept = new javax.swing.JButton();
        car_li = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();
        cid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 520));
        setMinimumSize(new java.awt.Dimension(800, 520));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 520));
        setSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(null);

        search.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(220, 110, 71, 23);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(720, 470, 73, 23);

        accept.setText("ACCEPT");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });
        getContentPane().add(accept);
        accept.setBounds(10, 470, 100, 23);

        car_li.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        car_li.setText("-");
        getContentPane().add(car_li);
        car_li.setBounds(130, 340, 220, 15);

        car.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        car.setText("-");
        getContentPane().add(car);
        car.setBounds(80, 300, 270, 15);

        cname.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cname.setText("-");
        getContentPane().add(cname);
        cname.setBounds(110, 220, 340, 15);

        cid.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cid.setText("-");
        getContentPane().add(cid);
        cid.setBounds(90, 260, 190, 15);

        jLabel9.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jLabel9.setText("Car License Number:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 340, 120, 15);

        jLabel7.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jLabel7.setText("Car Booked:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 300, 80, 15);

        jLabel6.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jLabel6.setText("Customer ID:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 260, 80, 15);

        jLabel5.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jLabel5.setText("Customer Name:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 93, 15);

        jLabel3.setFont(new java.awt.Font("Raleway", 0, 16)); // NOI18N
        jLabel3.setText("Bill Details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 180, 100, 20);

        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        getContentPane().add(bill);
        bill.setBounds(60, 110, 140, 20);

        jLabel2.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel2.setText("Bill ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 70, 20);

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel1.setText("Return");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 120, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        // TODO add your handling code here:
        if(flag == 0){
        String sql4 = "UPDATE vehicles SET avail = avail+1 WHERE name = ?";
        //String sql5 = "UPDATE license_plate SET avail = 'y' WHERE car_state = ? and car_lic = ?;";
        String sql6 = "";
        /*updating vehicles*/
        try{
        ps = con.prepareStatement(sql4);
        ps.setString(1,model);
        int r = ps.executeUpdate();
        if(r>0){
            JOptionPane.showMessageDialog(null,"Return Successfull!");
        }
        else{
            JOptionPane.showMessageDialog(null,"Didn't work");
        }
        /*
        ps = con.prepareStatement(sql5);
        ps.setString(1,car_state);
        ps.setInt(2,car_lic);
        r = ps.executeUpdate();
        if(r>1){
            JOptionPane.showMessageDialog(null,"license plate updated Successfull!");
        }
        else{
            JOptionPane.showMessageDialog(null,"Didn't work");
        }
        */
        
        PreparedStatement pst = con.prepareStatement("UPDATE booking SET status = 'p' WHERE book_id = ?");
        pst.setString(1,bill.getText());
        int x = pst.executeUpdate();
        if(x>0){
            JOptionPane.showMessageDialog(null,"Bookings updated!");
        }
        
        mainscreen s = new mainscreen();
        s.setVisible(true);
        close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        /***********************************/
        }
        
    }//GEN-LAST:event_acceptActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        mainscreen s = new mainscreen();
        s.setVisible(true);
        close();
    }//GEN-LAST:event_backActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        String sql1 = "SELECT * FROM booking WHERE book_id = ?;";
        String sql2 = "SELECT name FROM customer WHERE cust_id = ?";
        String sql3 = "SELECT brand, model FROM license_plate WHERE state_code IN (SELECT car_state FROM booking where book_id = ?) AND license_no IN (SELECT car_lic FROM booking where book_id = ?);";
        
        try{
            //book_id, car_state, car_lic, cust_id, days, fare;
            
            /*getting car licence and customer id*/
            ps = con.prepareStatement(sql1);
            ps.setString(1,bill.getText());
            rs = ps.executeQuery();
            while(rs.next())
            {
              if(rs.getString("status").equals("p"))
              {
                  /*Updating the screen*/
                  cname.setText("-");
                  cid.setText("-");
                  car.setText("-");
                  car_li.setText("-");
                  /***********************************/
                  JOptionPane.showMessageDialog(null, "This transaction is already over.");
                  flag = 1;
              }
              else{
                  car_state = rs.getString("car_state");
                  car_lic = rs.getInt("car_lic");
                  cust_id = rs.getInt("cust_id");
                  flag = 0;
              }
            }
            /************************************/
            
            if(flag == 0){
            /*getting customer name*/
            ps = con.prepareStatement(sql2);
            ps.setString(1,String.valueOf(cust_id));
            rs = ps.executeQuery();
            while(rs.next())
            {
                name = rs.getString("name");
            }
            /************************************/
            
            /*getting carname*/
            
            ps = con.prepareStatement(sql3);
            ps.setString(1,bill.getText());     //changes made here
            ps.setString(2,bill.getText());
            rs = ps.executeQuery();
            while(rs.next())
            {
                brand = rs.getString("brand");
                model = rs.getString("model");
            }
        
            /***********************************/
            
            /*Updating the screen*/
            cname.setText(name);
            cid.setText(String.valueOf(cust_id));
            car.setText(brand + " " + model);
            car_li.setText(car_state + " " + String.valueOf(car_lic));
            /***********************************/
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new return_car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField bill;
    private javax.swing.JLabel car;
    private javax.swing.JLabel car_li;
    private javax.swing.JLabel cid;
    private javax.swing.JLabel cname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
